"""initial migration

Revision ID: 81831356359d
Revises: 
Create Date: 2023-12-06 13:38:42.918360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81831356359d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('collection_item',
    sa.Column('movie_id', sa.String(length=100), nullable=False),
    sa.Column('movie_title', sa.String(length=100), nullable=True),
    sa.Column('movie_year', sa.String(length=100), nullable=True),
    sa.Column('actors', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('genre', sa.String(length=200), nullable=True),
    sa.Column('user_score', sa.String(length=3), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('movie_id'),
    sa.UniqueConstraint('movie_id'),
    sa.UniqueConstraint('movie_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_item')
    op.drop_table('user')
    # ### end Alembic commands ###
